### ISSUE TITLE
loopr-page  browser calculate ".sections" elements paddingTop incorrectly at page first loaded

### ISSUE THREAD

**Issue by bung87** [Loopring/loopr#134]
related variables:
multi slots 

scroll region

expecting:

paddingTop as like loopr-toolbar existed

current:

paddingTop as like loopr-toolbar not existed,makes like loopr-toolbar float at paddingTop Area.

this can be solved by adding extros styles to .sections at shared-styles and subpage styles.
also add some code on loopr-page ready callback.

related doc: https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-undefined-elements

**Comment by dong77** [comment]
@bung87 can you help us do this? I have no clue so far...

**Comment by dong77** [comment]
@bung87 I'll send you 1000LRC for this. As I don't know how to fix it.

**Comment by bung87** [comment]
@dong77 Thanks! I'm working on a project base on this project ,it's pretty looks and good api mock data ,thanks for you guys's work.

**Comment by dong77** [comment]
please send your ETH address to me, my email is daniel@loopring.org. Thank you so much for this fix, @bung87 .

**Comment by bung87** [comment]
@dong77 here is my address: 0xb3890D22885be3489a86d0fD4715417fA608e1eE

**Comment by dong77** [comment]
It seems you are quite into crypto (based what you starred on github). Any specific crypto-projects are you working on?

Tx will be sent to you soon with 1200LRC: https://etherscan.io/tx/0x230cb90f008252502e4ce9398819256edc273ff64e0c0a7573f1f6f81e1522b7

**Comment by dong77** [comment]
Let me know if if the TX doesn’t go through in an hour:)

**Comment by bung87** [comment]
nope,I only known basic theory and can use some related library. my major skill is  website development specifically front-end,I also use python or nodejs for backend development or some scripts.

**Comment by dong77** [comment]
If you have time, we welcome you to continue contributing to our frontend project. We have another one here: https://github.com/Loopring/web-widget <https://github.com/Loopring/web-widget>

**Comment by bung87** [comment]
I have some ideas to improve this project and I've add some features to my forked version which pushed on private git host ,but have no ideas about this project roadmap,so if you can provide some roadmap information,let me see what I can do for improving.

we can discus with wechat : daizystripper . and speaking in chinese.

**Comment by dong77** [comment]
talk to you tomorrow.

**Comment by dong77** [comment]
BTW, I found your last PR is inconsistent between these two pages: https://loopr.io/#/history <https://loopr.io/#/history> and https://loopr.io/#/markets <https://loopr.io/#/markets> which caused different paddings. The first one is much taller than the second one. It will be great if you can give it a quick fix.

**Comment by bung87** [comment]
I dont know what the designed padding top value is ,so I just leave it as it was,you meaning make history page and markets page have same padding top ? 可以直接提供写入权限么 ？

**Comment by bung87** [comment]
@dong77 says "Sorry, We are unable to locate the Transaction Hash"
