### ISSUE TITLE
Display an error when http/https returns error!

### ISSUE THREAD

**Issue by dong77** [Loopring/loopr#171]

**Comment by dyfvicture** [comment]
When call relay API return errors by component "loopr-relay-ajax":
![image](https://user-images.githubusercontent.com/6755466/33817773-3541e23a-de7c-11e7-8426-59c28291125b.png)

When loading initial config return errors by component "loopr-ajax":
![image](https://user-images.githubusercontent.com/6755466/33817795-5f66c4b8-de7c-11e7-9d1e-ee0ef1a9ada9.png)
