### ISSUE TITLE
dependency loopring.js confliction

### ISSUE THREAD

**Issue by bung87** [Loopring/loopr#185]
https://github.com/Loopring/loopr/blob/b3ab8787ef948838f321fb941a8e42f28450d2ae/src/external-lib-imports.html#L9

https://github.com/Loopring/loopring.js documented it as:
```
<script src="../bower_components/loopring.js/dist/loopring.min.js"></script>
```

https://github.com/Loopring/loopring.js/commit/aabae3c840149ec52a22fdfe1a47fe94c6aebe3a

as the loopring.js repository cleaned the dist directory and has no post install action will make this project broken.

**Comment by lyddream** [comment]
we now publish loopring.js to npm, so we mange loopring.js in package.json and import it in the way of  <script src="../node_modules/loopring.js/dist/loopring.min.js"></script>
