### ISSUE TITLE
Missing "see more link" on market page

### ISSUE THREAD

**Issue by dong77** [Loopring/loopr#57]
There should be a "see more" link on the bottom of "recent orders", "recent trades", "my recent orders", and "my recent trades".

**Comment by dyfvicture** [comment]
Done.
https://github.com/Loopring/looper/pull/70

**Comment by dong77** [comment]
In different market, clicking "see more ..." should redirect to a different url, such as:
http://127.0.0.1:8081/#/history/trades?market=lrc-eth

**Comment by dyfvicture** [comment]
Done: https://github.com/Loopring/loopr/pull/77.
For keeping in consistent format, use Rest (#/history/orders/LRC-WETH)
